name: Laravel PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4  # Adjust to your Laravel version
        extensions: mbstring, xml, zip, pdo, bcmath, ctype, json, tokenizer, xmlwriter

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Install PHPStan
      run: composer require --dev phpstan/phpstan

    - name: Set up Laravel
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache

    - name: Check PHP syntax for files in resources/views
      run: find resources/views -name "*.php" -exec php -l {} \;

    - name: Compile Blade templates
      run: php artisan view:cache

    - name: Run PHPStan Analysis
      run: vendor/bin/phpstan analyze --level=7

    # Add additional Laravel setup and testing steps here

    # - name: Run Laravel tests
    #   run: php artisan test
